/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ArteController;
import Interfaces.ArteSelecionadoListener;
import Model.Arte;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class CadArteView extends javax.swing.JFrame  implements ArteSelecionadoListener{
    ArteController controller = new ArteController();
    /**
     * Creates new form CadArteView
     */
    public CadArteView() {
        initComponents();
        TxtArteId.setEditable(false);
        TxtArteId.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbArteTitulo = new javax.swing.JLabel();
        LbArteId = new javax.swing.JLabel();
        LbArteUrl = new javax.swing.JLabel();
        TxtArteId = new javax.swing.JTextField();
        TxtArteUrl = new javax.swing.JTextField();
        BtNovo = new javax.swing.JButton();
        BtCarregarImagem = new javax.swing.JToggleButton();
        BtGravar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        LbImagem = new javax.swing.JLabel();
        TxtArteNome = new javax.swing.JTextField();
        LbArteUrl1 = new javax.swing.JLabel();
        BtConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbArteTitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbArteTitulo.setText("Cadastro de Arte");

        LbArteId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbArteId.setText("ID:");

        LbArteUrl.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbArteUrl.setText("URL:");

        TxtArteId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtArteIdActionPerformed(evt);
            }
        });

        BtNovo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        BtCarregarImagem.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtCarregarImagem.setText("Carregar Imagem");
        BtCarregarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCarregarImagemActionPerformed(evt);
            }
        });

        BtGravar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtExcluir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        LbArteUrl1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbArteUrl1.setText("Nome:");

        BtConsultar.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        BtConsultar.setText("🔍");
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LbArteTitulo)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(BtNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtCarregarImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbArteUrl)
                                    .addComponent(LbArteUrl1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(LbArteId)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtArteUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(28, 28, 28))
                            .addComponent(TxtArteNome, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtArteId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtConsultar)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbArteTitulo)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbArteId)
                        .addComponent(TxtArteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbArteUrl)
                    .addComponent(TxtArteUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtArteNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbArteUrl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCarregarImagem)
                    .addComponent(BtNovo)
                    .addComponent(BtGravar)
                    .addComponent(BtExcluir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCarregarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCarregarImagemActionPerformed
        String caminho = TxtArteUrl.getText(); // campo onde está o caminho da imagem

    if (caminho != null && !caminho.isEmpty()) {
        ImageIcon imagem = new ImageIcon(caminho);
        Image imgRedimensionada = imagem.getImage().getScaledInstance(
            LbImagem.getWidth(),
            LbImagem.getHeight(),
            Image.SCALE_SMOOTH
        );
        LbImagem.setIcon(new ImageIcon(imgRedimensionada));
    } else {
        JOptionPane.showMessageDialog(this, "Caminho da imagem inválido.");
    }
    }//GEN-LAST:event_BtCarregarImagemActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        limparCampos();
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        Arte arte = new Arte(); 
        
        arte.setImagem(TxtArteUrl.getText());
        arte.setNome(TxtArteNome.getText());
        
        if(controller.inserir(arte)){
            JOptionPane.showMessageDialog(this, "Arte Cadastrada");
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar arte.");
        }
        limparCampos();
    }//GEN-LAST:event_BtGravarActionPerformed

    private void TxtArteIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtArteIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtArteIdActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        if(controller.excluir(Integer.parseInt(TxtArteId.getText()))){
            limparCampos();
            JOptionPane.showMessageDialog(this, "Arte Excluida");
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao excluir arte.");
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        
        ConsultaArteView consulta = new ConsultaArteView(this);
        consulta.setVisible(true);
   
    }//GEN-LAST:event_BtConsultarActionPerformed

    /**
     * Connection conn = // sua conexão com o banco
PreparedStatement stmt = conn.prepareStatement("SELECT url FROM arte WHERE id = ?");
stmt.setInt(1, idArte);
ResultSet rs = stmt.executeQuery();

if (rs.next()) {
    String caminho = rs.getString("url");
    TxtArteUrl.setText(caminho);
}
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadArteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadArteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadArteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadArteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadArteView().setVisible(true);
            }
        });
    }
    
    public void limparCampos() {
        TxtArteId.setText("");
        TxtArteUrl.setText("");
        TxtArteNome.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtCarregarImagem;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JLabel LbArteId;
    private javax.swing.JLabel LbArteTitulo;
    private javax.swing.JLabel LbArteUrl;
    private javax.swing.JLabel LbArteUrl1;
    private javax.swing.JLabel LbImagem;
    private javax.swing.JTextField TxtArteId;
    private javax.swing.JTextField TxtArteNome;
    private javax.swing.JTextField TxtArteUrl;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onArteSelecionada(Arte arte) {
        TxtArteId.setText(String.valueOf(arte.getId()));
        TxtArteUrl.setText(String.valueOf(arte.getImagem()));
        TxtArteNome.setText(String.valueOf(arte.getNome()));
    }
}
