/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ClienteController;
import Interfaces.ClienteSelecionadoListener;
import Model.Cliente;
import javax.swing.JOptionPane;
/**
 *
 * @author Aluno
 */
public class CadClienteView extends javax.swing.JFrame implements ClienteSelecionadoListener {

    /**
     * Creates new form CadClienteView
     */
    ClienteController controller = new ClienteController();
    
    public CadClienteView() {
        initComponents();
        TxtIdCli.setEditable(false);
        TxtIdCli.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbCadCli = new javax.swing.JLabel();
        LbIdCli = new javax.swing.JLabel();
        LbNomeCli = new javax.swing.JLabel();
        LbCpfCli = new javax.swing.JLabel();
        LbRuaCli = new javax.swing.JLabel();
        LbNumeroCli = new javax.swing.JLabel();
        LbBairroCli = new javax.swing.JLabel();
        LbCidadeCLi = new javax.swing.JLabel();
        LbArteAnterior = new javax.swing.JLabel();
        TxtIdCli = new javax.swing.JTextField();
        TxtCpfCli = new javax.swing.JTextField();
        TxtNomeCli = new javax.swing.JTextField();
        TxtRuaCli = new javax.swing.JTextField();
        TxtNumeroCli = new javax.swing.JTextField();
        TxtBairroCli = new javax.swing.JTextField();
        txtCidadeCli = new javax.swing.JTextField();
        BtNovo = new javax.swing.JButton();
        BtConsultar = new javax.swing.JButton();
        BtGravar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        TxtArteCli = new javax.swing.JTextField();
        MenuCadCli = new javax.swing.JMenuBar();
        MenuContratos = new javax.swing.JMenu();
        MenuContratosCadastrados = new javax.swing.JMenuItem();
        MenuArtes = new javax.swing.JMenu();
        MenuArtesAnteriores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbCadCli.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbCadCli.setText("Cadastro de Cliente");

        LbIdCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbIdCli.setText("ID:");

        LbNomeCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbNomeCli.setText("Nome:");

        LbCpfCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbCpfCli.setText("CPF:");

        LbRuaCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbRuaCli.setText("Rua:");

        LbNumeroCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbNumeroCli.setText("Numero:");

        LbBairroCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbBairroCli.setText("Bairro:");

        LbCidadeCLi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbCidadeCLi.setText("Cidade:");

        LbArteAnterior.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbArteAnterior.setText("Arte Anterior:");

        TxtIdCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdCliActionPerformed(evt);
            }
        });

        TxtNumeroCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeroCliActionPerformed(evt);
            }
        });

        BtNovo.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        BtConsultar.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        BtConsultar.setText("🔍");
        BtConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        BtGravar.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtAlterar.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtAlterar.setText("Alterar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtExcluir.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        TxtArteCli.setText("0");
        TxtArteCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtArteCliActionPerformed(evt);
            }
        });

        MenuContratos.setText("Contratos");

        MenuContratosCadastrados.setText("Contratos cadastrados");
        MenuContratosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContratosCadastradosActionPerformed(evt);
            }
        });
        MenuContratos.add(MenuContratosCadastrados);

        MenuCadCli.add(MenuContratos);

        MenuArtes.setText("Artes");

        MenuArtesAnteriores.setText("Cadastrar Arte");
        MenuArtesAnteriores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArtesAnterioresActionPerformed(evt);
            }
        });
        MenuArtes.add(MenuArtesAnteriores);

        MenuCadCli.add(MenuArtes);

        setJMenuBar(MenuCadCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(LbCadCli))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(LbRuaCli))
                                    .addComponent(LbNomeCli))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LbCidadeCLi))
                                            .addComponent(TxtRuaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LbNumeroCli)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtNumeroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(TxtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LbArteAnterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtArteCli, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(LbBairroCli)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbCpfCli)
                            .addComponent(LbIdCli))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(BtNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LbCadCli)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbCpfCli)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TxtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeCli)
                    .addComponent(TxtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRuaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRuaCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNumeroCli)
                    .addComponent(TxtNumeroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbBairroCli)
                    .addComponent(LbCidadeCLi)
                    .addComponent(TxtBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbArteAnterior)
                    .addComponent(TxtArteCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovo)
                    .addComponent(BtGravar)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNumeroCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeroCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeroCliActionPerformed

    private void TxtIdCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdCliActionPerformed

    private void MenuContratosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContratosCadastradosActionPerformed
        TelaCadContrato novaTela = new TelaCadContrato();
        novaTela.setVisible(true);
    }//GEN-LAST:event_MenuContratosCadastradosActionPerformed

    private void MenuArtesAnterioresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArtesAnterioresActionPerformed
        CadArteView novaArte = new CadArteView();
        novaArte.setVisible(true);
    }//GEN-LAST:event_MenuArtesAnterioresActionPerformed

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed

        ConsultaClienteView consulta = new ConsultaClienteView(this);
        consulta.setVisible(true);
      
    }//GEN-LAST:event_BtConsultarActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        Cliente cliente = new Cliente(); 
        cliente.setArteId(Integer.parseInt(TxtArteCli.getText()));
        cliente.setCpf(Integer.parseInt(TxtCpfCli.getText()));
        cliente.setNome(TxtNomeCli.getText());
        cliente.setRua(TxtRuaCli.getText());
        cliente.setBairro(TxtBairroCli.getText());
        cliente.setNumero(Integer.parseInt(TxtNumeroCli.getText()));
        cliente.setCidade(txtCidadeCli.getText());
        if(controller.inserirCliente(cliente)){
            JOptionPane.showMessageDialog(this, "Cliente Cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao inserir cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void TxtArteCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtArteCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtArteCliActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        limparCampos();
        TxtCpfCli.requestFocus();
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        Cliente cliente = new Cliente();
        cliente.setArteId(Integer.parseInt(TxtArteCli.getText()));
        cliente.setId(Integer.parseInt(TxtIdCli.getText()));
        cliente.setCpf(Integer.parseInt(TxtCpfCli.getText()));
        cliente.setNome(TxtNomeCli.getText());
        cliente.setRua(TxtRuaCli.getText());
        cliente.setBairro(TxtBairroCli.getText());
        cliente.setNumero(Integer.parseInt(TxtNumeroCli.getText()));
        cliente.setCidade(txtCidadeCli.getText());
        if(controller.atualizarCliente(cliente)){
            JOptionPane.showMessageDialog(this, "Cliente alterado");
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar Cliente", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        if(controller.excluirCliente(Integer.parseInt(TxtIdCli.getText()))){
            JOptionPane.showMessageDialog(this, "Cliente Excluido", "Erro", JOptionPane.ERROR_MESSAGE);
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir Produto", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadClienteView().setVisible(true);
            }
        });
    }
    public void preencherCampos(String id, String cpf, String nome, String rua, String numero, String bairro, String cidade, String arte) {
        TxtIdCli.setText(id);
        TxtCpfCli.setText(cpf);
        TxtNomeCli.setText(nome);
        TxtRuaCli.setText(rua);
        TxtNumeroCli.setText(numero);
        TxtBairroCli.setText(bairro);
        txtCidadeCli.setText(cidade);
        TxtArteCli.setText(arte);
    }
    public void limparCampos() {
        TxtIdCli.setText("");
        TxtCpfCli.setText("");
        TxtNomeCli.setText("");
        TxtRuaCli.setText("");
        TxtNumeroCli.setText("");
        TxtBairroCli.setText("");
        txtCidadeCli.setText("");
        TxtArteCli.setText("");
    }
    @Override
public void onClienteSelecionado(Cliente cliente) {
    TxtIdCli.setText(String.valueOf(cliente.getId()));
    TxtCpfCli.setText(String.valueOf(cliente.getCpf()));
    TxtNomeCli.setText(cliente.getNome());
    TxtRuaCli.setText(cliente.getRua());
    TxtNumeroCli.setText(String.valueOf(cliente.getNumero()));
    TxtBairroCli.setText(cliente.getBairro());
    txtCidadeCli.setText(cliente.getCidade());
    TxtArteCli.setText(String.valueOf(cliente.getArteId()));
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JLabel LbArteAnterior;
    private javax.swing.JLabel LbBairroCli;
    private javax.swing.JLabel LbCadCli;
    private javax.swing.JLabel LbCidadeCLi;
    private javax.swing.JLabel LbCpfCli;
    private javax.swing.JLabel LbIdCli;
    private javax.swing.JLabel LbNomeCli;
    private javax.swing.JLabel LbNumeroCli;
    private javax.swing.JLabel LbRuaCli;
    private javax.swing.JMenu MenuArtes;
    private javax.swing.JMenuItem MenuArtesAnteriores;
    private javax.swing.JMenuBar MenuCadCli;
    private javax.swing.JMenu MenuContratos;
    private javax.swing.JMenuItem MenuContratosCadastrados;
    private javax.swing.JTextField TxtArteCli;
    private javax.swing.JTextField TxtBairroCli;
    private javax.swing.JTextField TxtCpfCli;
    private javax.swing.JTextField TxtIdCli;
    private javax.swing.JTextField TxtNomeCli;
    private javax.swing.JTextField TxtNumeroCli;
    private javax.swing.JTextField TxtRuaCli;
    private javax.swing.JTextField txtCidadeCli;
    // End of variables declaration//GEN-END:variables
}
