/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Aluno
 */
public class CadClienteView extends javax.swing.JFrame {

    /**
     * Creates new form CadClienteView
     */
    public CadClienteView() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbCadCli = new javax.swing.JLabel();
        LbIdCli = new javax.swing.JLabel();
        LbNomeCli = new javax.swing.JLabel();
        LbCpfCli = new javax.swing.JLabel();
        LbRuaCli = new javax.swing.JLabel();
        LbNumeroCli = new javax.swing.JLabel();
        LbBairroCli = new javax.swing.JLabel();
        LbCidadeCLi = new javax.swing.JLabel();
        TxtIdCLi = new javax.swing.JTextField();
        TxtCpfCLi = new javax.swing.JTextField();
        TxtNomeCLi = new javax.swing.JTextField();
        TxtRuaCLi = new javax.swing.JTextField();
        TxtNumeroCLi = new javax.swing.JTextField();
        TxtBairroCli = new javax.swing.JTextField();
        txtCidadeCli = new javax.swing.JTextField();
        BtNovo = new javax.swing.JButton();
        BtConsultar = new javax.swing.JButton();
        BtGravar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        MenuCadCli = new javax.swing.JMenuBar();
        MenuContratos = new javax.swing.JMenu();
        MenuContratosCadastrados = new javax.swing.JMenuItem();
        MenuArtes = new javax.swing.JMenu();
        MenuArtesAnteriores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbCadCli.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbCadCli.setText("Cadastro de Cliente");

        LbIdCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbIdCli.setText("ID:");

        LbNomeCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbNomeCli.setText("Nome:");

        LbCpfCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbCpfCli.setText("CPF:");

        LbRuaCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbRuaCli.setText("Rua:");

        LbNumeroCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbNumeroCli.setText("Numero:");

        LbBairroCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbBairroCli.setText("Bairro:");

        LbCidadeCLi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbCidadeCLi.setText("Cidade:");

        TxtIdCLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdCLiActionPerformed(evt);
            }
        });

        TxtNumeroCLi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeroCLiActionPerformed(evt);
            }
        });

        BtNovo.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtNovo.setText("Novo");

        BtConsultar.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        BtConsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        BtGravar.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtGravar.setText("Gravar");

        BtAlterar.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtAlterar.setText("Alterar");

        BtExcluir.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtExcluir.setText("Excluir");

        MenuContratos.setText("Contratos");

        MenuContratosCadastrados.setText("Contratos cadastrados");
        MenuContratosCadastrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuContratosCadastradosActionPerformed(evt);
            }
        });
        MenuContratos.add(MenuContratosCadastrados);

        MenuCadCli.add(MenuContratos);

        MenuArtes.setText("Artes");

        MenuArtesAnteriores.setText("Cadastrar Arte");
        MenuArtesAnteriores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArtesAnterioresActionPerformed(evt);
            }
        });
        MenuArtes.add(MenuArtesAnteriores);

        MenuCadCli.add(MenuArtes);

        setJMenuBar(MenuCadCli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(LbCadCli))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(LbRuaCli))
                                    .addComponent(LbNomeCli))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LbCidadeCLi))
                                            .addComponent(TxtRuaCLi, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(LbNumeroCli)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TxtNumeroCLi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(TxtNomeCLi, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(LbBairroCli))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbCpfCli)
                            .addComponent(LbIdCli))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(BtNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtIdCLi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtCpfCLi, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LbCadCli)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdCLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbCpfCli)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TxtCpfCLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeCli)
                    .addComponent(TxtNomeCLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbRuaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRuaCLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbNumeroCli)
                    .addComponent(TxtNumeroCLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbBairroCli)
                    .addComponent(LbCidadeCLi)
                    .addComponent(TxtBairroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovo)
                    .addComponent(BtGravar)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNumeroCLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeroCLiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeroCLiActionPerformed

    private void TxtIdCLiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdCLiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdCLiActionPerformed

    private void MenuContratosCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuContratosCadastradosActionPerformed
        TelaCadContrato novaTela = new TelaCadContrato();
        novaTela.setVisible(true);
    }//GEN-LAST:event_MenuContratosCadastradosActionPerformed

    private void MenuArtesAnterioresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArtesAnterioresActionPerformed
        CadArteView novaArte = new CadArteView();
        novaArte.setVisible(true);
    }//GEN-LAST:event_MenuArtesAnterioresActionPerformed

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
       
       //
    }//GEN-LAST:event_BtConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JLabel LbBairroCli;
    private javax.swing.JLabel LbCadCli;
    private javax.swing.JLabel LbCidadeCLi;
    private javax.swing.JLabel LbCpfCli;
    private javax.swing.JLabel LbIdCli;
    private javax.swing.JLabel LbNomeCli;
    private javax.swing.JLabel LbNumeroCli;
    private javax.swing.JLabel LbRuaCli;
    private javax.swing.JMenu MenuArtes;
    private javax.swing.JMenuItem MenuArtesAnteriores;
    private javax.swing.JMenuBar MenuCadCli;
    private javax.swing.JMenu MenuContratos;
    private javax.swing.JMenuItem MenuContratosCadastrados;
    private javax.swing.JTextField TxtBairroCli;
    private javax.swing.JTextField TxtCpfCLi;
    private javax.swing.JTextField TxtIdCLi;
    private javax.swing.JTextField TxtNomeCLi;
    private javax.swing.JTextField TxtNumeroCLi;
    private javax.swing.JTextField TxtRuaCLi;
    private javax.swing.JTextField txtCidadeCli;
    // End of variables declaration//GEN-END:variables
}
