/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ProdutoController;
import Model.Produto;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class CadProView extends javax.swing.JFrame {
 ProdutoController controller = new ProdutoController();
    /**
     * Creates new form CadProView
     */
    public CadProView() {
        initComponents();
        TxtIdPro.setEditable(false);
        TxtIdPro.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbCadProTitulo = new javax.swing.JLabel();
        LbIdPro = new javax.swing.JLabel();
        LbDescricaoPro = new javax.swing.JLabel();
        LbValorPro = new javax.swing.JLabel();
        LbEstoquePro = new javax.swing.JLabel();
        TxtIdPro = new javax.swing.JTextField();
        TxtDescricaoPro = new javax.swing.JTextField();
        TxtValorPro = new javax.swing.JTextField();
        TxtEstoquePro = new javax.swing.JTextField();
        BtGravar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtNovo = new javax.swing.JButton();
        BtConsultar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbCadProTitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbCadProTitulo.setText("Cadastro de Produto");

        LbIdPro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbIdPro.setText("ID:");

        LbDescricaoPro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbDescricaoPro.setText("Descrição:");

        LbValorPro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbValorPro.setText("Valor:");

        LbEstoquePro.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbEstoquePro.setText("Estoque:");

        BtGravar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtAlterar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtAlterar.setText("Alterar");

        BtNovo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtNovo.setText("Novo");

        BtConsultar.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        BtConsultar.setText("🔍");
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        BtExcluir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtExcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(LbCadProTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(LbIdPro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(BtConsultar)))
                        .addGap(0, 174, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbValorPro)
                                    .addComponent(LbDescricaoPro)
                                    .addComponent(LbEstoquePro))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtValorPro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtDescricaoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtEstoquePro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LbCadProTitulo)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbIdPro)
                        .addComponent(TxtIdPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDescricaoPro)
                    .addComponent(TxtDescricaoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtValorPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbValorPro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEstoquePro)
                    .addComponent(TxtEstoquePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtExcluir)
                    .addComponent(BtAlterar)
                    .addComponent(BtGravar)
                    .addComponent(BtNovo))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
 Produto produto = new Produto();
    

    int id = 0;
    if (!TxtIdPro.getText().trim().isEmpty()) {
        try {
            id = Integer.parseInt(TxtIdPro.getText());
            produto.setId(id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    produto.setDescricao(TxtDescricaoPro.getText());
    produto.setValor(Float.parseFloat(TxtValorPro.getText()));
    produto.setQuantidade(Integer.parseInt(TxtEstoquePro.getText()));

    boolean sucesso;

    if (id > 0 && controller.buscarProduto(id) != null) {
        // Produto existe → Atualizar
        sucesso = controller.atualizarProduto(produto);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar o produto.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Produto não existe → Inserir
        sucesso = controller.inserirProduto(produto);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o produto.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        ConsultaProdutoView consulta = new ConsultaProdutoView(this);
        consulta.setVisible(true);
    }//GEN-LAST:event_BtConsultarActionPerformed
    public void preencherCampos(String id, String descricao, String valor, String estoque) {
        TxtIdPro.setText(id);
        TxtDescricaoPro.setText(descricao);
        TxtValorPro.setText(valor);
        TxtEstoquePro.setText(estoque);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JLabel LbCadProTitulo;
    private javax.swing.JLabel LbDescricaoPro;
    private javax.swing.JLabel LbEstoquePro;
    private javax.swing.JLabel LbIdPro;
    private javax.swing.JLabel LbValorPro;
    private javax.swing.JTextField TxtDescricaoPro;
    private javax.swing.JTextField TxtEstoquePro;
    private javax.swing.JTextField TxtIdPro;
    private javax.swing.JTextField TxtValorPro;
    // End of variables declaration//GEN-END:variables
}
