/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.TatuadorController;
import Interfaces.TatuadorSelecionadoListener;
import Model.Tatuador;
import javax.swing.JOptionPane;


/**
 *
 * @author usuario
 */
public class CadTatuadorView extends javax.swing.JFrame implements 
    TatuadorSelecionadoListener{

    /**
     * Creates new form CadTatuadorView
     */
    public CadTatuadorView() {
        initComponents();
        TxtIdTatu.setEditable(false);
        TxtIdTatu.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbCadTatuador = new javax.swing.JLabel();
        LbIdTatu = new javax.swing.JLabel();
        LbNomeTatu = new javax.swing.JLabel();
        LbCpfTatu = new javax.swing.JLabel();
        LbRuaTatu = new javax.swing.JLabel();
        LbNumeroTatu = new javax.swing.JLabel();
        LbBairroTatu = new javax.swing.JLabel();
        LbCidadeTatu = new javax.swing.JLabel();
        LbEstiloTatu = new javax.swing.JLabel();
        LbTotalVendasTatu = new javax.swing.JLabel();
        TxtIdTatu = new javax.swing.JTextField();
        TxtCpfTatu = new javax.swing.JTextField();
        TxtNomeTatu = new javax.swing.JTextField();
        TxtRuaTatu = new javax.swing.JTextField();
        TxtNumeroTatu = new javax.swing.JTextField();
        TxtBairroTatu = new javax.swing.JTextField();
        txtCidadeTatu = new javax.swing.JTextField();
        TxtEstiloTatu = new javax.swing.JTextField();
        TxtTotalVendaTatu = new javax.swing.JTextField();
        BtNovo = new javax.swing.JButton();
        BtConsultar = new javax.swing.JButton();
        BtGravar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbCadTatuador.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbCadTatuador.setText("Cadastro de Tatuador");

        LbIdTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbIdTatu.setText("ID:");

        LbNomeTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbNomeTatu.setText("Nome:");

        LbCpfTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbCpfTatu.setText("CPF:");

        LbRuaTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbRuaTatu.setText("Rua:");

        LbNumeroTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbNumeroTatu.setText("Numero:");

        LbBairroTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbBairroTatu.setText("Bairro:");

        LbCidadeTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbCidadeTatu.setText("Cidade:");

        LbEstiloTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbEstiloTatu.setText("Estilo:");

        LbTotalVendasTatu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbTotalVendasTatu.setText("Vendas:");

        TxtIdTatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdTatuActionPerformed(evt);
            }
        });

        TxtNomeTatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeTatuActionPerformed(evt);
            }
        });

        TxtNumeroTatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumeroTatuActionPerformed(evt);
            }
        });

        BtNovo.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        BtConsultar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        BtConsultar.setText("🔍");
        BtConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarActionPerformed(evt);
            }
        });

        BtGravar.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtAlterar.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtAlterar.setText("Alterar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtExcluir.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbNomeTatu)
                                    .addComponent(LbRuaTatu)
                                    .addComponent(LbIdTatu)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(LbEstiloTatu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtNomeTatu, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(TxtIdTatu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtConsultar)))
                                .addGap(30, 30, 30)
                                .addComponent(LbCpfTatu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCpfTatu, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(322, 322, 322)
                                .addComponent(BtNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtEstiloTatu, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtRuaTatu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(TxtBairroTatu, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(LbTotalVendasTatu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtTotalVendaTatu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(132, 132, 132))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LbNumeroTatu)
                                            .addComponent(LbCidadeTatu))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtNumeroTatu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCidadeTatu)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(LbCadTatuador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(LbBairroTatu)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(LbCadTatuador)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbIdTatu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtIdTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNomeTatu)
                    .addComponent(TxtNomeTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCpfTatu)
                    .addComponent(TxtCpfTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbNumeroTatu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbRuaTatu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtRuaTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtNumeroTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbBairroTatu)
                    .addComponent(LbCidadeTatu)
                    .addComponent(TxtBairroTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEstiloTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstiloTatu)
                    .addComponent(LbTotalVendasTatu)
                    .addComponent(TxtTotalVendaTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovo)
                    .addComponent(BtGravar)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtIdTatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdTatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdTatuActionPerformed

    private void TxtNomeTatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeTatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeTatuActionPerformed

    private void TxtNumeroTatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumeroTatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumeroTatuActionPerformed

    private void BtConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarActionPerformed
        ConsultaTatuadorView consulta = new ConsultaTatuadorView(this);
        consulta.setVisible(true);
    }//GEN-LAST:event_BtConsultarActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        limparCampos();
        TxtNomeTatu.requestFocus();
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        try {
        Tatuador tatuador = new Tatuador();
        tatuador.setNome(TxtNomeTatu.getText());
        tatuador.setCpf(Integer.parseInt(TxtCpfTatu.getText()));
        tatuador.setRua(TxtRuaTatu.getText());
        tatuador.setNumero(Integer.parseInt(TxtNumeroTatu.getText()));
        tatuador.setBairro(TxtBairroTatu.getText());
        tatuador.setCidade(txtCidadeTatu.getText());
        tatuador.setEstilo(TxtEstiloTatu.getText());
        tatuador.setTotalVenda(Float.parseFloat(TxtTotalVendaTatu.getText()));

        TatuadorController controller = new TatuadorController();
        boolean sucesso = controller.inserirTatuador(tatuador);

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Tatuador gravado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao gravar tatuador.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique os valores numéricos!", "Erro de entrada", JOptionPane.WARNING_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
            try {
        Tatuador tatuador = new Tatuador();
        tatuador.setId(Integer.parseInt(TxtIdTatu.getText()));
        tatuador.setNome(TxtNomeTatu.getText());
        tatuador.setCpf(Integer.parseInt(TxtCpfTatu.getText()));
        tatuador.setRua(TxtRuaTatu.getText());
        tatuador.setNumero(Integer.parseInt(TxtNumeroTatu.getText()));
        tatuador.setBairro(TxtBairroTatu.getText());
        tatuador.setCidade(txtCidadeTatu.getText());
        tatuador.setEstilo(TxtEstiloTatu.getText());
        tatuador.setTotalVenda(Float.parseFloat(TxtTotalVendaTatu.getText()));

        TatuadorController controller = new TatuadorController();
        boolean atualizado = controller.atualizarTatuador(tatuador);

        if (atualizado) {
            JOptionPane.showMessageDialog(this, "Tatuador atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar tatuador.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique os valores numéricos!", "Erro de entrada", JOptionPane.WARNING_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try {
        if (TxtIdTatu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o ID do tatuador para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja excluir este tatuador?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(TxtIdTatu.getText());

            TatuadorController controller = new TatuadorController();
            boolean excluido = controller.excluirTatuador(id);

            if (excluido) {
                JOptionPane.showMessageDialog(this, "Tatuador excluído com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir tatuador.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido!", "Erro", JOptionPane.WARNING_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadTatuadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadTatuadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadTatuadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadTatuadorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadTatuadorView().setVisible(true);
            }
        });
    }
    public void onTatuadorSelecionado(Model.Tatuador tatuador) {
    if (tatuador != null) {
        TxtIdTatu.setText(String.valueOf(tatuador.getId()));
        TxtNomeTatu.setText(tatuador.getNome());
        TxtCpfTatu.setText(String.valueOf(tatuador.getCpf()));
        TxtRuaTatu.setText(tatuador.getRua());
        TxtNumeroTatu.setText(String.valueOf(tatuador.getNumero()));
        TxtBairroTatu.setText(tatuador.getBairro());
        txtCidadeTatu.setText(tatuador.getCidade());
        TxtEstiloTatu.setText(tatuador.getEstilo());
        TxtTotalVendaTatu.setText(String.valueOf(tatuador.getTotalVenda()));
    }
}
    public void limparCampos() {
    TxtIdTatu.setText("");
    TxtNomeTatu.setText("");
    TxtCpfTatu.setText("");
    TxtRuaTatu.setText("");
    TxtNumeroTatu.setText("");
    TxtBairroTatu.setText("");
    txtCidadeTatu.setText("");
    TxtEstiloTatu.setText("");
    TxtTotalVendaTatu.setText("");
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtNovo;
    private javax.swing.JLabel LbBairroTatu;
    private javax.swing.JLabel LbCadTatuador;
    private javax.swing.JLabel LbCidadeTatu;
    private javax.swing.JLabel LbCpfTatu;
    private javax.swing.JLabel LbEstiloTatu;
    private javax.swing.JLabel LbIdTatu;
    private javax.swing.JLabel LbNomeTatu;
    private javax.swing.JLabel LbNumeroTatu;
    private javax.swing.JLabel LbRuaTatu;
    private javax.swing.JLabel LbTotalVendasTatu;
    private javax.swing.JTextField TxtBairroTatu;
    private javax.swing.JTextField TxtCpfTatu;
    private javax.swing.JTextField TxtEstiloTatu;
    private javax.swing.JTextField TxtIdTatu;
    private javax.swing.JTextField TxtNomeTatu;
    private javax.swing.JTextField TxtNumeroTatu;
    private javax.swing.JTextField TxtRuaTatu;
    private javax.swing.JTextField TxtTotalVendaTatu;
    private javax.swing.JTextField txtCidadeTatu;
    // End of variables declaration//GEN-END:variables
}
