/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.ProdutoController;
import Model.Produto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author usuario
 */
public class ConsultaProdutoView extends javax.swing.JFrame {
    ProdutoController controller = new ProdutoController();

    /**
     * Creates new form ConsultaProdutoView
     */
    public ConsultaProdutoView() {
        initComponents();
        carregarTabela();
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada != -1) {
            String id = jTable1.getValueAt(linhaSelecionada, 0).toString();
            String descricao = jTable1.getValueAt(linhaSelecionada, 1).toString();
            String valor = jTable1.getValueAt(linhaSelecionada, 2).toString();
            String quantidade = jTable1.getValueAt(linhaSelecionada, 3).toString();

            LbId.setText(id);
            LbDescricao.setText(descricao);
            LbValor.setText(valor);
            LbQuantidade.setText(quantidade);
        }
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LbBuscar = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        ComboFiltro = new javax.swing.JComboBox<>();
        BtBuscar = new javax.swing.JButton();
        LbTituto = new javax.swing.JLabel();
        LbId = new javax.swing.JLabel();
        LbDescricao = new javax.swing.JLabel();
        LbValor = new javax.swing.JLabel();
        LbQuantidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        LbBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbBuscar.setText("Buscar:");

        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });

        ComboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Descrição", "Valor", "Quantidade" }));
        ComboFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboFiltroActionPerformed(evt);
            }
        });

        BtBuscar.setText("Buscar");
        BtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarActionPerformed(evt);
            }
        });

        LbTituto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbTituto.setText("Consulta de Produtos");

        LbId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbId.setText("ID");

        LbDescricao.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbDescricao.setText("Descricao");

        LbValor.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbValor.setText("Valor");

        LbQuantidade.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbQuantidade.setText("Quantidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(LbTituto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(357, 357, 357))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(LbId)
                        .addGap(169, 169, 169)
                        .addComponent(LbDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LbValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LbQuantidade)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTituto)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbId)
                    .addComponent(LbDescricao)
                    .addComponent(LbValor)
                    .addComponent(LbQuantidade))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbBuscar)
                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtBuscar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboFiltroActionPerformed
        
    }//GEN-LAST:event_ComboFiltroActionPerformed

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void BtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarActionPerformed
        aplicarFiltro();
    }//GEN-LAST:event_BtBuscarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
 
        if (evt.getClickCount() == 2) {
        int linha = jTable1.getSelectedRow();
        if (linha != -1) {
            String idStr = jTable1.getValueAt(linha, 0).toString();
            int id = Integer.parseInt(idStr);

            ProdutoController controller = new ProdutoController();
            Produto produto = controller.buscarProduto(id);

            if (produto != null) {
                //telaCadastro.preencherCampos(
                  //  String.valueOf(produto.getId()),
                    //produto.getDescricao(),
                    //String.valueOf(produto.getValor()),
                    //String.valueOf(produto.getQuantidade())
                //);
                this.dispose(); // Fecha a tela de consulta
            } else {
                JOptionPane.showMessageDialog(this, "Produto não encontrado.");
            }
        }
    }
    

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ConsultaProdutoView().setVisible(true);
            }
        });
    }

    public void carregarTabela() { 
        String pesquisa = "";
        String filtro = " WHERE descricao LIKE '%"+pesquisa+"%' or valor LIKE '%"+pesquisa+"%' or quantidade LIKE '%"+pesquisa+"%';";
        //  if(tem filtro){ muda o filtro) else( filtro = "") :)
        DefaultTableModel model = controller.carregarTabela(filtro);
        jTable1.setModel(model);
    }

    
    private void aplicarFiltro() {
    String textoBusca = TxtBuscar.getText().trim();
    String coluna = ComboFiltro.getSelectedItem().toString();

    String colunaBD = switch (coluna) {
        case "ID" -> "id";
        case "Descrição" -> "descricao";
        case "Valor" -> "valor";
        case "Quantidade" -> "quantidade";
        default -> "descricao"; 
    };
    

    String filtro = "";
    if (!textoBusca.isEmpty()) {
        filtro = " WHERE " + colunaBD + " LIKE '%" + textoBusca + "%'";
    }

    DefaultTableModel model = controller.carregarTabela(filtro);
    jTable1.setModel(model);
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBuscar;
    private javax.swing.JComboBox<String> ComboFiltro;
    private javax.swing.JLabel LbBuscar;
    private javax.swing.JLabel LbDescricao;
    private javax.swing.JLabel LbId;
    private javax.swing.JLabel LbQuantidade;
    private javax.swing.JLabel LbTituto;
    private javax.swing.JLabel LbValor;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
