/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Aluno
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbTitulo = new javax.swing.JLabel();
        BarraDeMenu = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuCadCli = new javax.swing.JMenuItem();
        MenuCadTat = new javax.swing.JMenuItem();
        MenuCadProd = new javax.swing.JMenuItem();
        MenuCadArte = new javax.swing.JMenuItem();
        MenuMovimentos = new javax.swing.JMenu();
        MenuMovOrc = new javax.swing.JMenuItem();
        MenuMovPed = new javax.swing.JMenuItem();
        MenuMovCont = new javax.swing.JMenuItem();
        MenuRelatorio = new javax.swing.JMenu();
        MenuRelProd = new javax.swing.JMenuItem();
        MenuRelCli = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LbTitulo.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        LbTitulo.setText("Tattool");
        LbTitulo.setToolTipText("");
        LbTitulo.setName("Tattool"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(LbTitulo)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(LbTitulo)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        MenuCadastros.setText("Cadastros");

        MenuCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        MenuCadCli.setText("Cadastrar Cliente");
        MenuCadastros.add(MenuCadCli);

        MenuCadTat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        MenuCadTat.setText("Cadastrar Tatuador");
        MenuCadastros.add(MenuCadTat);

        MenuCadProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        MenuCadProd.setText("Cadastrar Produto");
        MenuCadastros.add(MenuCadProd);

        MenuCadArte.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        MenuCadArte.setText("Cadastrar Arte");
        MenuCadastros.add(MenuCadArte);

        BarraDeMenu.add(MenuCadastros);

        MenuMovimentos.setText("Movimentos");

        MenuMovOrc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        MenuMovOrc.setText("Orçamento");
        MenuMovimentos.add(MenuMovOrc);

        MenuMovPed.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        MenuMovPed.setText("Pedido");
        MenuMovimentos.add(MenuMovPed);

        MenuMovCont.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        MenuMovCont.setText("Contrato");
        MenuMovimentos.add(MenuMovCont);

        BarraDeMenu.add(MenuMovimentos);

        MenuRelatorio.setText("Relatórios");

        MenuRelProd.setText("Produtos");
        MenuRelatorio.add(MenuRelProd);

        MenuRelCli.setText("Clientes");
        MenuRelatorio.add(MenuRelCli);

        BarraDeMenu.add(MenuRelatorio);

        setJMenuBar(BarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraDeMenu;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JMenuItem MenuCadArte;
    private javax.swing.JMenuItem MenuCadCli;
    private javax.swing.JMenuItem MenuCadProd;
    private javax.swing.JMenuItem MenuCadTat;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenuItem MenuMovCont;
    private javax.swing.JMenuItem MenuMovOrc;
    private javax.swing.JMenuItem MenuMovPed;
    private javax.swing.JMenu MenuMovimentos;
    private javax.swing.JMenuItem MenuRelCli;
    private javax.swing.JMenuItem MenuRelProd;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
