/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ItemController;
import Controller.OrcamentoController;
import Controller.ProdutoController;
import Interfaces.ArteSelecionadoListener;
import Interfaces.ClienteSelecionadoListener;
import Interfaces.ContratoSelecionadoListener;
import Interfaces.OrcamentoSelecionadoListener;
import Interfaces.ProdutoSelecionadoListener;
import Interfaces.TatuadorSelecionadoListener;
import Model.Arte;
import Model.Cliente;
import Model.Contrato;
import Model.ItemOrcamento;
import Model.Orcamento;
import Model.Produto;
import Model.Tatuador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class OrcamentoView extends javax.swing.JFrame implements 
    ClienteSelecionadoListener,
    TatuadorSelecionadoListener,
    ProdutoSelecionadoListener,
    ContratoSelecionadoListener,
    ArteSelecionadoListener,
    OrcamentoSelecionadoListener{

    /**
     * Creates new form CadastroView
     */
    public OrcamentoView() {
        initComponents();
        DefaultTableModel model = new DefaultTableModel(
            new Object[]{"ID", "Descrição", "Valor", "Quantidade", "Subtotal"}, 0
        );
        jTable1.setModel(model);
        carregarProdutos(0);
        desligarInserts();
    }
     
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTituto = new javax.swing.JLabel();
        LbIdOrc = new javax.swing.JLabel();
        LbCliId = new javax.swing.JLabel();
        LbTatuadorId = new javax.swing.JLabel();
        LbProduto = new javax.swing.JLabel();
        LbContratoId = new javax.swing.JLabel();
        LbArteId = new javax.swing.JLabel();
        LbMaoDeObra = new javax.swing.JLabel();
        LbTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TxtIdOrc = new javax.swing.JTextField();
        TxtIdCli = new javax.swing.JTextField();
        TxtIDTatu = new javax.swing.JTextField();
        TxtIdProduto = new javax.swing.JTextField();
        TxtIdContrato = new javax.swing.JTextField();
        TxtIdArte = new javax.swing.JTextField();
        BtConsultarOrc = new javax.swing.JButton();
        BtConsultarCli = new javax.swing.JButton();
        BtConsultarTatu = new javax.swing.JButton();
        BtConsultarPro = new javax.swing.JButton();
        BtConsultarContrato = new javax.swing.JButton();
        BtConsultarArte = new javax.swing.JButton();
        BtNovo = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtadicionarProduto = new javax.swing.JButton();
        CheckBoxAprovado = new javax.swing.JCheckBox();
        TxtMaodeObra = new javax.swing.JTextField();
        TxtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbTituto.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbTituto.setText("Orçamento");

        LbIdOrc.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbIdOrc.setText("ID:");

        LbCliId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbCliId.setText("Cliente:");

        LbTatuadorId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbTatuadorId.setText("Tatuador:");

        LbProduto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbProduto.setText("Produto:");

        LbContratoId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbContratoId.setText("Contrato:");

        LbArteId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbArteId.setText("Arte:");

        LbMaoDeObra.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbMaoDeObra.setText("Mão De obra:");

        LbTotal.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbTotal.setText("Total:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        TxtIdOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdOrcActionPerformed(evt);
            }
        });

        BtConsultarOrc.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        BtConsultarOrc.setText("🔍");
        BtConsultarOrc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultarOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarOrcActionPerformed(evt);
            }
        });

        BtConsultarCli.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        BtConsultarCli.setText("🔍");
        BtConsultarCli.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarCliActionPerformed(evt);
            }
        });

        BtConsultarTatu.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        BtConsultarTatu.setText("🔍");
        BtConsultarTatu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultarTatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarTatuActionPerformed(evt);
            }
        });

        BtConsultarPro.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        BtConsultarPro.setText("🔍");
        BtConsultarPro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarProActionPerformed(evt);
            }
        });

        BtConsultarContrato.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        BtConsultarContrato.setText("🔍");
        BtConsultarContrato.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarContratoActionPerformed(evt);
            }
        });

        BtConsultarArte.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        BtConsultarArte.setText("🔍");
        BtConsultarArte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultarArte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarArteActionPerformed(evt);
            }
        });

        BtNovo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtNovo.setText("Novo");
        BtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtNovoActionPerformed(evt);
            }
        });

        BtAlterar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtAlterar.setText("Gravar");
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtExcluir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtadicionarProduto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        BtadicionarProduto.setText("+");
        BtadicionarProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtadicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtadicionarProdutoActionPerformed(evt);
            }
        });

        CheckBoxAprovado.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        CheckBoxAprovado.setText("Aprovado");
        CheckBoxAprovado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxAprovadoActionPerformed(evt);
            }
        });

        TxtMaodeObra.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TxtMaodeObra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TxtMaodeObraFocusLost(evt);
            }
        });

        TxtTotal.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        TxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbCliId)
                                    .addComponent(LbTatuadorId)
                                    .addComponent(LbProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtIDTatu)
                                    .addComponent(TxtIdProduto)
                                    .addComponent(TxtIdCli, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(LbIdOrc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtIdOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtConsultarOrc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LbContratoId)
                                    .addComponent(LbArteId)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BtConsultarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtConsultarTatu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtConsultarPro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtadicionarProduto)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(LbTituto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtIdArte, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(TxtIdContrato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtConsultarContrato)
                            .addComponent(BtConsultarArte, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(CheckBoxAprovado))
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtExcluir)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbMaoDeObra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtMaodeObra, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LbTituto)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbIdOrc)
                            .addComponent(TxtIdOrc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtConsultarOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbContratoId)
                            .addComponent(TxtIdContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtConsultarContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LbArteId)
                                            .addComponent(TxtIdCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtIdArte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtConsultarArte, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(LbCliId)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BtConsultarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbTatuadorId)
                            .addComponent(TxtIDTatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtConsultarTatu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CheckBoxAprovado)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbProduto)
                            .addComponent(TxtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtConsultarPro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(BtadicionarProduto)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbMaoDeObra)
                    .addComponent(TxtMaodeObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbTotal)
                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtNovo)
                    .addComponent(BtAlterar)
                    .addComponent(BtExcluir))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtConsultarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarCliActionPerformed

    ConsultaClienteView consulta = new ConsultaClienteView(this); 
    consulta.setVisible(true);

    }//GEN-LAST:event_BtConsultarCliActionPerformed

    private void BtConsultarTatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarTatuActionPerformed
        ConsultaTatuadorView consulta = new ConsultaTatuadorView(this);
        consulta.setVisible(true);
    }//GEN-LAST:event_BtConsultarTatuActionPerformed

    private void BtConsultarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarProActionPerformed
        ConsultaProdutoView consulta = new ConsultaProdutoView(this); // 'this' implementa ProdutoSelecionadoListener
        consulta.setVisible(true);
    }//GEN-LAST:event_BtConsultarProActionPerformed

    private void BtConsultarOrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarOrcActionPerformed
        ConsultaOrcamentoView consulta = new ConsultaOrcamentoView(this);
        consulta.setVisible(true);
        ligarInserts();
    }//GEN-LAST:event_BtConsultarOrcActionPerformed

    private void BtConsultarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarContratoActionPerformed
        ConsultaContratoView consulta = new ConsultaContratoView(this);
        consulta.setVisible(true);
    }//GEN-LAST:event_BtConsultarContratoActionPerformed

    private void BtConsultarArteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarArteActionPerformed
        ConsultaArteView consulta = new ConsultaArteView(this);
        consulta.setVisible(true);
    }//GEN-LAST:event_BtConsultarArteActionPerformed

    private void TxtIdOrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdOrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdOrcActionPerformed

    private void CheckBoxAprovadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxAprovadoActionPerformed

        
        
        
    }//GEN-LAST:event_CheckBoxAprovadoActionPerformed

    private void BtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtNovoActionPerformed
        limparCampos();
        TxtIdCli.requestFocus();
        TxtIDTatu.setText("0");
        TxtIdArte.setText("0");
        TxtIdCli.setText("0");
        TxtIdContrato.setText("0");
        TxtMaodeObra.setText("0");
        TxtTotal.setText("0");
        TxtIdProduto.setText("0");
       
        Orcamento orcamento = new Orcamento();
        
        orcamento.setCliente(Integer.parseInt(TxtIdCli.getText()));
        orcamento.setTatuador(Integer.parseInt(TxtIDTatu.getText()));
        orcamento.setContratoId(Integer.parseInt(TxtIdContrato.getText()));
        orcamento.setArte(Integer.parseInt(TxtIdArte.getText()));
        orcamento.setAprovado(CheckBoxAprovado.isSelected());
        orcamento.setMaoDeObra(Float.parseFloat(TxtMaodeObra.getText()));
        orcamento.setTotal(Float.parseFloat(TxtTotal.getText()));
        
        OrcamentoController controller = new OrcamentoController();
        controller.inserirOrcamento(orcamento);
        TxtIdOrc.setText(String.valueOf(controller.buscarUltimoOrcamentoId()));
        ligarInserts();
    }//GEN-LAST:event_BtNovoActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
            try {
        Orcamento orcamento = new Orcamento();

        orcamento.setId(Integer.parseInt(TxtIdOrc.getText()));
        orcamento.setCliente(Integer.parseInt(TxtIdCli.getText()));
        orcamento.setTatuador(Integer.parseInt(TxtIDTatu.getText()));
        orcamento.setContratoId(Integer.parseInt(TxtIdContrato.getText()));
        orcamento.setArte(Integer.parseInt(TxtIdArte.getText()));
        orcamento.setAprovado(CheckBoxAprovado.isSelected());
        orcamento.setMaoDeObra(Float.parseFloat(TxtMaodeObra.getText()));
        orcamento.setTotal(Float.parseFloat(TxtTotal.getText()));

        boolean atualizado = new OrcamentoController().atualizarOrcamento(orcamento);

        if (atualizado) {
            JOptionPane.showMessageDialog(this, "Orçamento atualizado.");
            desligarInserts();
            limparCampos();
            carregarProdutos(0);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar.");
        }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        try {
            int id = Integer.parseInt(TxtIdOrc.getText());

            int confirmar = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir?", "Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirmar == JOptionPane.YES_OPTION) {
                boolean excluido = new OrcamentoController().excluirOrcamento(id);
                if (excluido) {
                    JOptionPane.showMessageDialog(this, "Orçamento excluído.");
                    desligarInserts();
                    limparCampos();
                    carregarProdutos(0);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtadicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtadicionarProdutoActionPerformed
        try {
            int idProduto = Integer.parseInt(TxtIdProduto.getText());
            int idOrcamento = Integer.parseInt(TxtIdOrc.getText());
            ItemController itemController = new ItemController();
            ProdutoController controller = new ProdutoController();
            Produto produto = controller.buscarProduto(idProduto);
            ItemOrcamento item = new ItemOrcamento();

            if (produto != null) {
                // INSERIR ITEM NA TABELA
                item.setOrcamento_id(idOrcamento);
                item.setProduto_id(idProduto);
                
                itemController.inserirItem(item);
                // BUSCAR NA TABELA ITEM PASSANDO ID
                carregarProdutos(idOrcamento);
                atualizarTotal();
            } else {
                JOptionPane.showMessageDialog(this, "Produto não encontrado.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar item: " + e.getMessage());
        }
    }//GEN-LAST:event_BtadicionarProdutoActionPerformed

    private void TxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalActionPerformed

    private void TxtMaodeObraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TxtMaodeObraFocusLost
        atualizarTotal();
    }//GEN-LAST:event_TxtMaodeObraFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrcamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrcamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrcamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrcamentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrcamentoView().setVisible(true);
            }
        });
    }
    @Override
public void onClienteSelecionado(Cliente cliente) {
    TxtIdCli.setText(String.valueOf(cliente.getId()));
}

@Override
public void onTatuadorSelecionado(Tatuador tatuador) {
    TxtIDTatu.setText(String.valueOf(tatuador.getId()));
}

@Override
public void onProdutoSelecionado(Produto produto) {
    TxtIdProduto.setText(String.valueOf(produto.getId()));
}

@Override
public void onContratoSelecionado(Contrato contrato) {
    TxtIdContrato.setText(String.valueOf(contrato.getId()));
}

@Override
public void onArteSelecionada(Arte arte) {
    TxtIdArte.setText(String.valueOf(arte.getId()));
}

public void onOrcametoSelecionado(Orcamento orcamento){
    TxtIdOrc.setText(String.valueOf(orcamento.getId()));
    TxtIdArte.setText(String.valueOf(orcamento.getArte()));
    TxtIdCli.setText(String.valueOf(orcamento.getCliente()));
    TxtIdContrato.setText(String.valueOf(orcamento.getContratoId()));
    TxtMaodeObra.setText(String.valueOf(orcamento.getMaoDeObra())); 
    TxtTotal.setText(String.valueOf(orcamento.getTotal()));
    TxtIdProduto.setText(String.valueOf(orcamento.getProduto()));
    TxtIDTatu.setText(String.valueOf(orcamento.getTatuador()));
    if(orcamento.getAprovado()){
        CheckBoxAprovado.setSelected(true);
    }
    carregarProdutos(orcamento.getId());
    atualizarTotal();
}

public void carregarProdutos(int id){
    ItemController controller = new ItemController();
    String filtro = " WHERE orcamento_id = " + id;
    DefaultTableModel model = controller.carregarTabela(filtro);
    jTable1.setModel(model);
}

public void desligarInserts(){
    TxtIDTatu.setEnabled(false);
    TxtIdArte.setEnabled(false);
    TxtIdCli.setEnabled(false);
    TxtIdContrato.setEnabled(false);
    TxtIdOrc.setEnabled(false);
    TxtMaodeObra.setEnabled(false);
    TxtTotal.setEnabled(false);
    TxtIdProduto.setEnabled(false);
    BtAlterar.setEnabled(false);
    BtConsultarArte.setEnabled(false);
    BtConsultarCli.setEnabled(false);
    BtConsultarContrato.setEnabled(false);
    BtConsultarPro.setEnabled(false);
    BtConsultarTatu.setEnabled(false);
    BtExcluir.setEnabled(false);
    BtadicionarProduto.setEnabled(false);
    CheckBoxAprovado.setEnabled(false);
}
public void ligarInserts() {
    TxtIDTatu.setEnabled(true);
    TxtIdArte.setEnabled(true);
    TxtIdCli.setEnabled(true);
    TxtIdContrato.setEnabled(true);
    TxtIdOrc.setEnabled(true);
    TxtMaodeObra.setEnabled(true);
    TxtTotal.setEnabled(true);
    TxtIdProduto.setEnabled(true);
    BtAlterar.setEnabled(true);
    BtConsultarArte.setEnabled(true);
    BtConsultarCli.setEnabled(true);
    BtConsultarContrato.setEnabled(true);
    BtConsultarPro.setEnabled(true);
    BtConsultarTatu.setEnabled(true);
    BtExcluir.setEnabled(true);
    BtadicionarProduto.setEnabled(true);
    CheckBoxAprovado.setEnabled(true);
}
public void limparCampos() {
    TxtIDTatu.setText("");
    TxtIdArte.setText("");
    TxtIdCli.setText("");
    TxtIdContrato.setText("");
    TxtIdOrc.setText("");
    TxtMaodeObra.setText("");
    TxtTotal.setText("");
    TxtIdProduto.setText("");
}
    private void atualizarTotal() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        double total = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            Object valorObj = model.getValueAt(i, 3); // Coluna valor

            if (valorObj != null) {
                try {
                    if (valorObj instanceof Number) {
                        total += ((Number) valorObj).doubleValue();
                    } else {
                        total += Double.parseDouble(valorObj.toString());
                    }
                } catch (Exception e) {
                    System.out.println("Erro ao somar valor na linha " + i + ": " + e.getMessage());
                }
            }
        }
        total += Double.parseDouble(TxtMaodeObra.getText());
        float totalFloat = (float) total; // total é double
        TxtTotal.setText(String.format("%.2f", totalFloat));
        TxtTotal.setText(TxtTotal.getText().replace(",", "."));
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtConsultarArte;
    private javax.swing.JButton BtConsultarCli;
    private javax.swing.JButton BtConsultarContrato;
    private javax.swing.JButton BtConsultarOrc;
    private javax.swing.JButton BtConsultarPro;
    private javax.swing.JButton BtConsultarTatu;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtNovo;
    private javax.swing.JButton BtadicionarProduto;
    private javax.swing.JCheckBox CheckBoxAprovado;
    private javax.swing.JLabel LbArteId;
    private javax.swing.JLabel LbCliId;
    private javax.swing.JLabel LbContratoId;
    private javax.swing.JLabel LbIdOrc;
    private javax.swing.JLabel LbMaoDeObra;
    private javax.swing.JLabel LbProduto;
    private javax.swing.JLabel LbTatuadorId;
    private javax.swing.JLabel LbTituto;
    private javax.swing.JLabel LbTotal;
    private javax.swing.JTextField TxtIDTatu;
    private javax.swing.JTextField TxtIdArte;
    private javax.swing.JTextField TxtIdCli;
    private javax.swing.JTextField TxtIdContrato;
    private javax.swing.JTextField TxtIdOrc;
    private javax.swing.JTextField TxtIdProduto;
    private javax.swing.JTextField TxtMaodeObra;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
