/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author usuario
 */
public class TelaCadContrato extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadContrato
     */
    public TelaCadContrato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTitutoCadContrato = new javax.swing.JLabel();
        LbContratoId = new javax.swing.JLabel();
        LbContratoCli = new javax.swing.JLabel();
        LbContatoTexto = new javax.swing.JLabel();
        TxtContratoId = new javax.swing.JTextField();
        TxtControtoCli = new javax.swing.JTextField();
        TxbContratoTexto = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BtContratoNovo = new javax.swing.JButton();
        BtContratoConsultar = new javax.swing.JButton();
        BtContratoGravar = new javax.swing.JButton();
        BtContratoAlterar = new javax.swing.JButton();
        BtContratoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbTitutoCadContrato.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbTitutoCadContrato.setText("Cadastro de contrato");

        LbContratoId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbContratoId.setText("ID:");

        LbContratoCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbContratoCli.setText("Cliente:");

        LbContatoTexto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbContatoTexto.setText("Texto:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        TxbContratoTexto.setViewportView(jTextArea1);

        BtContratoNovo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoNovo.setText("Novo");
        BtContratoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtContratoNovoActionPerformed(evt);
            }
        });

        BtContratoConsultar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoConsultar.setText("Consultar");

        BtContratoGravar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoGravar.setText("Gravar");

        BtContratoAlterar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoAlterar.setText("Alterar");

        BtContratoExcluir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoExcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(LbTitutoCadContrato))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(LbContatoTexto)
                            .addGap(18, 18, 18)
                            .addComponent(TxbContratoTexto))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LbContratoCli)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(LbContratoId)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtControtoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtContratoId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(BtContratoNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtContratoConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtContratoGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtContratoAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtContratoExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTitutoCadContrato)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbContratoId)
                    .addComponent(TxtContratoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbContratoCli)
                    .addComponent(TxtControtoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbContatoTexto)
                    .addComponent(TxbContratoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtContratoConsultar)
                    .addComponent(BtContratoGravar)
                    .addComponent(BtContratoAlterar)
                    .addComponent(BtContratoExcluir)
                    .addComponent(BtContratoNovo))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtContratoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtContratoNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtContratoNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtContratoAlterar;
    private javax.swing.JButton BtContratoConsultar;
    private javax.swing.JButton BtContratoExcluir;
    private javax.swing.JButton BtContratoGravar;
    private javax.swing.JButton BtContratoNovo;
    private javax.swing.JLabel LbContatoTexto;
    private javax.swing.JLabel LbContratoCli;
    private javax.swing.JLabel LbContratoId;
    private javax.swing.JLabel LbTitutoCadContrato;
    private javax.swing.JScrollPane TxbContratoTexto;
    private javax.swing.JTextField TxtContratoId;
    private javax.swing.JTextField TxtControtoCli;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
