/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ContratoController;
import Model.Contrato;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class TelaCadContrato extends javax.swing.JFrame {
ContratoController controller = new ContratoController();
    /**
     * Creates new form TelaCadContrato
     */
    public TelaCadContrato() {
        initComponents();
        TxtContratoId.setEditable(false);
        TxtContratoId.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTitutoCadContrato = new javax.swing.JLabel();
        LbContratoId = new javax.swing.JLabel();
        LbContratoCli = new javax.swing.JLabel();
        LbContatoTexto = new javax.swing.JLabel();
        LbCliNome = new javax.swing.JLabel();
        TxtContratoId = new javax.swing.JTextField();
        TxtContratoCli = new javax.swing.JTextField();
        TxbContratoTexto = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BtContratoNovo = new javax.swing.JButton();
        BtContratoConsultar = new javax.swing.JButton();
        BtContratoGravar = new javax.swing.JButton();
        BtContratoAlterar = new javax.swing.JButton();
        BtContratoExcluir = new javax.swing.JButton();
        BtConsultarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LbTitutoCadContrato.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LbTitutoCadContrato.setText("Cadastro de contrato");

        LbContratoId.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbContratoId.setText("ID:");

        LbContratoCli.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbContratoCli.setText("Cliente:");

        LbContatoTexto.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LbContatoTexto.setText("Texto:");

        LbCliNome.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        TxbContratoTexto.setViewportView(jTextArea1);

        BtContratoNovo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoNovo.setText("Novo");
        BtContratoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtContratoNovoActionPerformed(evt);
            }
        });

        BtContratoConsultar.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        BtContratoConsultar.setText("🔍");
        BtContratoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtContratoConsultarActionPerformed(evt);
            }
        });

        BtContratoGravar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoGravar.setText("Gravar");
        BtContratoGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtContratoGravarActionPerformed(evt);
            }
        });

        BtContratoAlterar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoAlterar.setText("Alterar");
        BtContratoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtContratoAlterarActionPerformed(evt);
            }
        });

        BtContratoExcluir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BtContratoExcluir.setText("Excluir");
        BtContratoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtContratoExcluirActionPerformed(evt);
            }
        });

        BtConsultarCliente.setFont(new java.awt.Font("Segoe UI Emoji", 3, 12)); // NOI18N
        BtConsultarCliente.setText("🔍");
        BtConsultarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(LbTitutoCadContrato))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(BtContratoNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtContratoGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtContratoAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtContratoExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(LbContatoTexto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxbContratoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbContratoCli)
                                    .addComponent(LbContratoId, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtContratoId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtContratoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtConsultarCliente)
                                    .addComponent(BtContratoConsultar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbCliNome, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTitutoCadContrato)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtContratoConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtContratoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbContratoId))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbContratoCli)
                            .addComponent(TxtContratoCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbCliNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbContatoTexto)
                            .addComponent(TxbContratoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtContratoGravar)
                            .addComponent(BtContratoAlterar)
                            .addComponent(BtContratoExcluir)
                            .addComponent(BtContratoNovo)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtConsultarCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtContratoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtContratoNovoActionPerformed
    limparCampos();
    TxtContratoCli.requestFocus();
    }//GEN-LAST:event_BtContratoNovoActionPerformed

    private void BtContratoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtContratoConsultarActionPerformed
        ConsultaContratoView consulta = new ConsultaContratoView(this);
        consulta.setVisible(true);
    }//GEN-LAST:event_BtContratoConsultarActionPerformed

    private void BtContratoGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtContratoGravarActionPerformed
    Contrato contrato = new Contrato();
    

    int id = 0;
    if (!TxtContratoId.getText().trim().isEmpty()) {
        try {
            id = Integer.parseInt(TxtContratoId.getText());
            contrato.setId(id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }

    contrato.setClienteId(Integer.parseInt(TxtContratoCli.getText()));
    contrato.setDados((jTextArea1.getText()));
    

    boolean sucesso;

    if (id > 0 && controller.buscarContrato(id) != null) {
        
        sucesso = controller.atualizarContrato(contrato);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Contrato atualizado com sucesso!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar o Contrato.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } else {
       
        sucesso = controller.inserirContrato(contrato);
        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Contrato cadastrado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar o Contrato.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_BtContratoGravarActionPerformed

    private void BtContratoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtContratoAlterarActionPerformed
        try {
        
        Contrato contrato = new Contrato();
        contrato.setId(Integer.parseInt(TxtContratoId.getText()));
        contrato.setClienteId(Integer.parseInt(TxtContratoCli.getText()));
        contrato.setDados((jTextArea1.getText()));

        
        ContratoController controller = new ContratoController();
        boolean atualizado = controller.atualizarContrato(contrato);

        
        if (atualizado) {
            JOptionPane.showMessageDialog(this, "contrato atualizado com sucesso!", "Atualização", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar contrato!", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique os valores numéricos!", "Erro de entrada", JOptionPane.WARNING_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtContratoAlterarActionPerformed

    private void BtContratoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtContratoExcluirActionPerformed
        try {
        
        if (TxtContratoId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o ID do contrato para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirmacao = JOptionPane.showConfirmDialog(this, 
            "Tem certeza que deseja excluir este contrato?", 
            "Confirmação", 
            JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            int id = Integer.parseInt(TxtContratoId.getText());

            ContratoController controller = new ContratoController();
            boolean excluido = controller.excluirContrato(id);

            if (excluido) {
                JOptionPane.showMessageDialog(this, "contrato excluído com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir contrato.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido!", "Erro", JOptionPane.WARNING_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro inesperado: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtContratoExcluirActionPerformed

    private void BtConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultarClienteActionPerformed
        CadClienteView telaCadastro = new CadClienteView();
        ConsultaClienteView consulta = new ConsultaClienteView(telaCadastro);
        consulta.setVisible(true);
    }//GEN-LAST:event_BtConsultarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadContrato().setVisible(true);
            }
        });
    }
        public void preencherCampos(String id, String cliente_id, String dados) {
        TxtContratoId.setText(id);
        TxtContratoCli.setText(cliente_id);
        jTextArea1.setText(dados);
        
    }
    public void limparCampos() {
    TxtContratoId.setText("");
    TxtContratoCli.setText("");
    jTextArea1.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConsultarCliente;
    private javax.swing.JButton BtContratoAlterar;
    private javax.swing.JButton BtContratoConsultar;
    private javax.swing.JButton BtContratoExcluir;
    private javax.swing.JButton BtContratoGravar;
    private javax.swing.JButton BtContratoNovo;
    private javax.swing.JLabel LbCliNome;
    private javax.swing.JLabel LbContatoTexto;
    private javax.swing.JLabel LbContratoCli;
    private javax.swing.JLabel LbContratoId;
    private javax.swing.JLabel LbTitutoCadContrato;
    private javax.swing.JScrollPane TxbContratoTexto;
    private javax.swing.JTextField TxtContratoCli;
    private javax.swing.JTextField TxtContratoId;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
